require 'pry'
require 'nokogiri'
require 'open-uri'
require 'net/http'
require 'json'

require_relative '../lib/cli'
# require_relative '../lib/worlds_best_restaurants/restaurant'
# require_relative '../lib/worlds_best_restaurants/cli'
# require_relative '../lib/worlds_best_restaurants/version'